imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: framework.yml }
    - { resource: doctrine.yml }
    - { resource: twig.yml }
    - { resource: stof_doctrine_extensions.yml }
    - { resource: swiftmailer.yml }
    - { resource: assetic.yml }
    - { resource: knp_menu.yml }
    - { resource: knp_paginator.yml }
    - { resource: braincrafted.yml }
    - { resource: vich_uploader.yml }
    - { resource: liip_imagine.yml }

parameters:
    locale: es

