kore_product:
    resource: "@KoreProductBundle/Resources/config/routing.yml"
    prefix:   /kore/product

kore_front:
    resource: "@KoreFrontBundle/Resources/config/routing.yml"
    prefix:   /

kore_page:
    resource: "@KorePageBundle/Resources/config/routing.yml"
    prefix:   /kore/page

kore_pablo:
    resource: "@KorePabloBundle/Resources/config/routing.yml"
    prefix: /kore/pablo
