paymentmethod_index:
    path:     /
    defaults: { _controller: "KoreProductBundle:PaymentMethod:index" }
    methods:  GET

paymentmethod_show:
    path:     /{id}/show
    defaults: { _controller: "KoreProductBundle:PaymentMethod:show" }
    methods:  GET

paymentmethod_new:
    path:     /new
    defaults: { _controller: "KoreProductBundle:PaymentMethod:new" }
    methods:  [GET, POST]

paymentmethod_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreProductBundle:PaymentMethod:edit" }
    methods:  [GET, POST]

paymentmethod_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreProductBundle:PaymentMethod:delete" }
    methods:  DELETE
