productimage_index:
    path:     /
    defaults: { _controller: "KoreProductBundle:ProductImage:index" }
    methods:  GET

productimage_show:
    path:     /{id}/show
    defaults: { _controller: "KoreProductBundle:ProductImage:show" }
    methods:  GET

productimage_new:
    path:     /new
    defaults: { _controller: "KoreProductBundle:ProductImage:new" }
    methods:  [GET, POST]

productimage_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreProductBundle:ProductImage:edit" }
    methods:  [GET, POST]

productimage_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreProductBundle:ProductImage:delete" }
    methods:  DELETE
