productorder_index:
    path:     /
    defaults: { _controller: "KoreProductBundle:ProductOrder:index" }
    methods:  GET

productorder_show:
    path:     /{id}/show
    defaults: { _controller: "KoreProductBundle:ProductOrder:show" }
    methods:  GET

productorder_new:
    path:     /new
    defaults: { _controller: "KoreProductBundle:ProductOrder:new" }
    methods:  [GET, POST]

productorder_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreProductBundle:ProductOrder:edit" }
    methods:  [GET, POST]

productorder_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreProductBundle:ProductOrder:delete" }
    methods:  DELETE
